Repository smalti/gmock-win32, pull requests merged in 2023-10, with the labels that each got.

#6 [proposed bug] Optimize off
  include/gmock-win32.h
Labels: bug

#7 Enhancement: Avoid using winApi directly in core
  src/gmock-win32.cpp
Labels: enhancement

#9 boolean, and keep init order
  src/gmock-win32.cpp
Labels: bug, enhancement

#8 [bug] deadlock in the setup of expectations for the mocked GetCurrentThreadId function
  include/gmock-win32.h
  src/gmock-win32.cpp
Labels: bug

#15 [documentation] update README.md
  README.md
Labels: documentation

#18 possible fix: fatal error LNK1169, one or more multiply defined symbo…
  include/gmock-win32.h
Labels: bug

#19 updated README.md for the next tag
  README.md
Labels: documentation

#20 There was a problem with AppCompat in earlier versions.
  README.md
Labels: documentation

#24 updated README.md for the next tag
  README.md
Labels: documentation
